server:
  port: 6060
  error:
    include-message: always

spring:
  application:
    name: customer-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_customer_service
    username: postgres
    password: magadiflo

  # API Versioning (Spring Boot 4)
  webflux:
    api-version:
      required: true
      supported: 1,2
      use:
        path-segment: 1

logging:
  level:
    io.r2dbc.postgresql.QUERY: debug
    io.r2dbc.postgresql.PARAM: debug
