server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: webflux-playground
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_webflux_playground
    username: postgres
    password: magadiflo

logging:
  level:
    io.r2dbc.postgresql.QUERY: debug
    io.r2dbc.postgresql.PARAM: debug

section: sec05
